# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

os:
  - linux
  # - osx

julia:
  - 1
  # - nightly

matrix:
  allow_failures:
    - julia: nightly

notifications:
  email: false

# avoid duplicate tests in PRs
branches:
  only:
    - master
    - dev

after_success:
  # push coverage results to Coveralls
  - julia -e 'using Pkg; cd(Pkg.dir("SummationByPartsOperators")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'using Pkg; cd(Pkg.dir("SummationByPartsOperators")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
