
"""
    MattssonAlmquistVanDerWeide2018Accurate()

Coefficients of the optimized SBP operators with nonuniform grid given in
- Mattsson, Almquist, van der Weide (2018)
  Boundary optimized diagonal-norm SBP operators.
  Journal of Computational Physics 374, pp. 1261-1266.
"""
struct MattssonAlmquistVanDerWeide2018Accurate <: SourceOfCoefficients end

function Base.show(io::IO, source::MattssonAlmquistVanDerWeide2018Accurate)
    if get(io, :compact, false)
        summary(io, source)
    else
        print(io,
              "Mattsson, Almquist, van der Weide (2018) \n",
              "  Boundary optimized diagonal-norm SBP operators ('Accurate'). \n",
              "  Journal of Computational Physics 374, pp. 1261-1266.")
    end
end

function construct_grid(::MattssonAlmquistVanDerWeide2018Accurate, accuracy_order, xmin,
                        xmax, N)
    @argcheck N > 6
    T = promote_type(typeof(xmin), typeof(xmax))

    # `xstart` contains only the non-uniform grid points 0, ξ₁, ..., ξₙ of the
    # reference, measured in units of the interior grid spacing. The equispaced
    # points following them are generated by `BoundaryAdaptedGrid`. Listing
    # them here as well would yield the same grid but increase the minimal
    # number of nodes required to construct the operator.
    if accuracy_order == 4
        xstart = SVector(T(0.0000000000000e+00),
                         T(6.8764546205559e-01),
                         T(1.8022115125776e+00))
    elseif accuracy_order == 6
        xstart = SVector(T(0.0000000000000e+00),
                         T(4.4090263368623e-01),
                         T(1.2855984345073e+00),
                         T(2.2638953951239e+00))
    elseif accuracy_order == 8
        xstart = SVector(T(0.0000000000000e+00),
                         T(3.8118550247622e-01),
                         T(1.1899550868338e+00),
                         T(2.2476300175641e+00),
                         T(3.3192851303204e+00))
    elseif accuracy_order == 10
        xstart = SVector(T(0.0000000000000e+00),
                         T(3.5902433622052e-01),
                         T(1.1436659188355e+00),
                         T(2.2144895894456e+00),
                         T(3.3682742337736e+00),
                         T(4.4309689056870e+00))
    elseif accuracy_order == 12
        xstart = SVector(T(0.0000000000000e+00),
                         T(3.6098032343909e-01),
                         T(1.1634317168086e+00),
                         T(2.2975905356987e+00),
                         T(3.6057529790929e+00),
                         T(4.8918275675510e+00),
                         T(6.0000000000000e+00))
    else
        throw(ArgumentError("Accuracy order $accuracy_order not implemented/derived."))
    end

    BoundaryAdaptedGrid(xmin, xmax, xstart, N)
end

function first_derivative_coefficients(source::MattssonAlmquistVanDerWeide2018Accurate,
                                       order::Int, T = Float64, mode = FastMode())
    if order == 4
        # interior stencil
        upper_coef = SVector(T(2 // 3), T(-1 // 12))
        central_coef = zero(T)
        lower_coef = -upper_coef

        # The diagonal norm `H` and the antisymmetric `Q` of the boundary
        # closure as printed in the paper, read as exact rational numbers.
        h1 = T(21259737557798 // 100000000000000)
        h2 = T(10260290400758 // 10000000000000)
        h3 = T(10775123588954 // 10000000000000)
        h4 = T(98607273802835 // 100000000000000)
        left_weights = SVector(h1, h2, h3, h4)

        q1_2 = T(65605279837843 // 100000000000000)
        q1_3 = T(-19875859409017 // 100000000000000)
        q1_4 = T(42705795711740 // 1000000000000000)
        q2_3 = T(81236966439895 // 100000000000000)
        q2_4 = T(-15631686602052 // 100000000000000)
        q3_4 = T(69694440364211 // 100000000000000)

        # `D[i, :] = (Q[i, :] - δ₁ᵢ e₁ᵀ / 2) / H[i, i]`. The entries reaching
        # beyond the boundary closure are fixed by the antisymmetry of `Q`:
        # row `j` uses the interior stencil and `H[j, j] = 1` there, so
        # `Q[i, j] = -Q[j, i] = upper_coef[j - i]`.
        left_boundary = (
                         # d1
                         DerivativeCoefficientRow{T, 1, 4}(SVector(-T(1 // 2) / h1,
                                                                   q1_2 / h1,
                                                                   q1_3 / h1,
                                                                   q1_4 / h1)),
                         # d2
                         DerivativeCoefficientRow{T, 1, 4}(SVector(-q1_2 / h2,
                                                                   T(0),
                                                                   q2_3 / h2,
                                                                   q2_4 / h2)),
                         # d3
                         DerivativeCoefficientRow{T, 1, 5}(SVector(-q1_3 / h3,
                                                                   -q2_3 / h3,
                                                                   T(0),
                                                                   q3_4 / h3,
                                                                   upper_coef[2] / h3)),
                         # d4
                         DerivativeCoefficientRow{T, 1, 6}(SVector(-q1_4 / h4,
                                                                   -q2_4 / h4,
                                                                   -q3_4 / h4,
                                                                   T(0),
                                                                   upper_coef[1] / h4,
                                                                   upper_coef[2] / h4)))
        right_boundary = .-left_boundary
        right_weights = left_weights
        left_boundary_derivatives = Tuple{}()
        right_boundary_derivatives = left_boundary_derivatives

        DerivativeCoefficients(left_boundary, right_boundary,
                               left_boundary_derivatives, right_boundary_derivatives,
                               lower_coef, central_coef, upper_coef,
                               left_weights, right_weights, mode, 1, order, source)
    elseif order == 6
        # interior stencil
        upper_coef = SVector(T(3 // 4), T(-3 // 20), T(1 // 60))
        central_coef = zero(T)
        lower_coef = -upper_coef

        # The diagonal norm `H` and the antisymmetric `Q` of the boundary
        # closure as printed in the paper, read as exact rational numbers.
        h1 = T(13030223027124 // 100000000000000)
        h2 = T(68851501587715 // 100000000000000)
        h3 = T(95166202564389 // 100000000000000)
        h4 = T(99103890475697 // 100000000000000)
        h5 = T(10028757074552 // 10000000000000)
        h6 = T(99950151111941 // 100000000000000)
        left_weights = SVector(h1, h2, h3, h4, h5, h6)

        q1_2 = T(66042071945824 // 100000000000000)
        q1_3 = T(-22104152954203 // 100000000000000)
        q1_4 = T(76243679810093 // 1000000000000000)
        q1_5 = T(-17298206716724 // 1000000000000000)
        q1_6 = T(16753369904210 // 10000000000000000)
        q2_3 = T(87352798702787 // 100000000000000)
        q2_4 = T(-26581719253084 // 100000000000000)
        q2_5 = T(57458484948314 // 1000000000000000)
        q2_6 = T(-47485599871040 // 10000000000000000)
        q3_4 = T(81707122038457 // 100000000000000)
        q3_5 = T(-18881125503769 // 100000000000000)
        q3_6 = T(24226492138960 // 1000000000000000)
        q4_5 = T(76798636652679 // 100000000000000)
        q4_6 = T(-15715532552963 // 100000000000000)
        q5_6 = T(75266872305402 // 100000000000000)

        # `D[i, :] = (Q[i, :] - δ₁ᵢ e₁ᵀ / 2) / H[i, i]`. The entries reaching
        # beyond the boundary closure are fixed by the antisymmetry of `Q`:
        # row `j` uses the interior stencil and `H[j, j] = 1` there, so
        # `Q[i, j] = -Q[j, i] = upper_coef[j - i]`.
        left_boundary = (
                         # d1
                         DerivativeCoefficientRow{T, 1, 6}(SVector(-T(1 // 2) / h1,
                                                                   q1_2 / h1,
                                                                   q1_3 / h1,
                                                                   q1_4 / h1,
                                                                   q1_5 / h1,
                                                                   q1_6 / h1)),
                         # d2
                         DerivativeCoefficientRow{T, 1, 6}(SVector(-q1_2 / h2,
                                                                   T(0),
                                                                   q2_3 / h2,
                                                                   q2_4 / h2,
                                                                   q2_5 / h2,
                                                                   q2_6 / h2)),
                         # d3
                         DerivativeCoefficientRow{T, 1, 6}(SVector(-q1_3 / h3,
                                                                   -q2_3 / h3,
                                                                   T(0),
                                                                   q3_4 / h3,
                                                                   q3_5 / h3,
                                                                   q3_6 / h3)),
                         # d4
                         DerivativeCoefficientRow{T, 1, 7}(SVector(-q1_4 / h4,
                                                                   -q2_4 / h4,
                                                                   -q3_4 / h4,
                                                                   T(0),
                                                                   q4_5 / h4,
                                                                   q4_6 / h4,
                                                                   upper_coef[3] / h4)),
                         # d5
                         DerivativeCoefficientRow{T, 1, 8}(SVector(-q1_5 / h5,
                                                                   -q2_5 / h5,
                                                                   -q3_5 / h5,
                                                                   -q4_5 / h5,
                                                                   T(0),
                                                                   q5_6 / h5,
                                                                   upper_coef[2] / h5,
                                                                   upper_coef[3] / h5)),
                         # d6
                         DerivativeCoefficientRow{T, 1, 9}(SVector(-q1_6 / h6,
                                                                   -q2_6 / h6,
                                                                   -q3_6 / h6,
                                                                   -q4_6 / h6,
                                                                   -q5_6 / h6,
                                                                   T(0),
                                                                   upper_coef[1] / h6,
                                                                   upper_coef[2] / h6,
                                                                   upper_coef[3] / h6)))
        right_boundary = .-left_boundary
        right_weights = left_weights
        left_boundary_derivatives = Tuple{}()
        right_boundary_derivatives = left_boundary_derivatives

        DerivativeCoefficients(left_boundary, right_boundary,
                               left_boundary_derivatives, right_boundary_derivatives,
                               lower_coef, central_coef, upper_coef,
                               left_weights, right_weights, mode, 1, order, source)
    elseif order == 8
        # interior stencil
        upper_coef = SVector(T(4 // 5), T(-1 // 5), T(4 // 105), T(-1 // 280))
        central_coef = zero(T)
        lower_coef = -upper_coef

        # The diagonal norm `H` and the antisymmetric `Q` of the boundary
        # closure as printed in the paper, read as exact rational numbers.
        h1 = T(10758368078310 // 100000000000000)
        h2 = T(61909685107891 // 100000000000000)
        h3 = T(96971176519117 // 100000000000000)
        h4 = T(11023441350947 // 10000000000000)
        h5 = T(10244688965833 // 10000000000000)
        h6 = T(99533550116831 // 100000000000000)
        h7 = T(10008236941028 // 10000000000000)
        h8 = T(99992060631812 // 100000000000000)
        left_weights = SVector(h1, h2, h3, h4, h5, h6, h7, h8)

        q1_2 = T(67284756079369 // 100000000000000)
        q1_3 = T(-25969732837062 // 100000000000000)
        q1_4 = T(13519390385721 // 100000000000000)
        q1_5 = T(-69678474730984 // 1000000000000000)
        q1_6 = T(26434024071371 // 1000000000000000)
        q1_7 = T(-55992311465618 // 10000000000000000)
        q1_8 = T(49954552590464 // 100000000000000000)
        q2_3 = T(94074021172233 // 100000000000000)
        q2_4 = T(-40511642426516 // 100000000000000)
        q2_5 = T(19369192209331 // 100000000000000)
        q2_6 = T(-68638079843479 // 1000000000000000)
        q2_7 = T(13146457241484 // 1000000000000000)
        q2_8 = T(-97652615479254 // 100000000000000000)
        q3_4 = T(94316393361096 // 100000000000000)
        q3_5 = T(-35728039257451 // 100000000000000)
        q3_6 = T(11266686855013 // 100000000000000)
        q3_7 = T(-18334941452280 // 1000000000000000)
        q3_8 = T(82741521740941 // 100000000000000000)
        q4_5 = T(87694387866575 // 100000000000000)
        q4_6 = T(-24698058719506 // 100000000000000)
        q4_7 = T(47291642094198 // 1000000000000000)
        q4_8 = T(-40135203618880 // 10000000000000000)
        q5_6 = T(81123946853807 // 100000000000000)
        q5_7 = T(-20267150541446 // 100000000000000)
        q5_8 = T(38680398901392 // 1000000000000000)
        q6_7 = T(80108544742793 // 100000000000000)
        q6_8 = T(-20088756283071 // 100000000000000)
        q7_8 = T(80039405922650 // 100000000000000)

        # `D[i, :] = (Q[i, :] - δ₁ᵢ e₁ᵀ / 2) / H[i, i]`. The entries reaching
        # beyond the boundary closure are fixed by the antisymmetry of `Q`:
        # row `j` uses the interior stencil and `H[j, j] = 1` there, so
        # `Q[i, j] = -Q[j, i] = upper_coef[j - i]`.
        left_boundary = (
                         # d1
                         DerivativeCoefficientRow{T, 1, 8}(SVector(-T(1 // 2) / h1,
                                                                   q1_2 / h1,
                                                                   q1_3 / h1,
                                                                   q1_4 / h1,
                                                                   q1_5 / h1,
                                                                   q1_6 / h1,
                                                                   q1_7 / h1,
                                                                   q1_8 / h1)),
                         # d2
                         DerivativeCoefficientRow{T, 1, 8}(SVector(-q1_2 / h2,
                                                                   T(0),
                                                                   q2_3 / h2,
                                                                   q2_4 / h2,
                                                                   q2_5 / h2,
                                                                   q2_6 / h2,
                                                                   q2_7 / h2,
                                                                   q2_8 / h2)),
                         # d3
                         DerivativeCoefficientRow{T, 1, 8}(SVector(-q1_3 / h3,
                                                                   -q2_3 / h3,
                                                                   T(0),
                                                                   q3_4 / h3,
                                                                   q3_5 / h3,
                                                                   q3_6 / h3,
                                                                   q3_7 / h3,
                                                                   q3_8 / h3)),
                         # d4
                         DerivativeCoefficientRow{T, 1, 8}(SVector(-q1_4 / h4,
                                                                   -q2_4 / h4,
                                                                   -q3_4 / h4,
                                                                   T(0),
                                                                   q4_5 / h4,
                                                                   q4_6 / h4,
                                                                   q4_7 / h4,
                                                                   q4_8 / h4)),
                         # d5
                         DerivativeCoefficientRow{T, 1, 9}(SVector(-q1_5 / h5,
                                                                   -q2_5 / h5,
                                                                   -q3_5 / h5,
                                                                   -q4_5 / h5,
                                                                   T(0),
                                                                   q5_6 / h5,
                                                                   q5_7 / h5,
                                                                   q5_8 / h5,
                                                                   upper_coef[4] / h5)),
                         # d6
                         DerivativeCoefficientRow{T, 1, 10}(SVector(-q1_6 / h6,
                                                                    -q2_6 / h6,
                                                                    -q3_6 / h6,
                                                                    -q4_6 / h6,
                                                                    -q5_6 / h6,
                                                                    T(0),
                                                                    q6_7 / h6,
                                                                    q6_8 / h6,
                                                                    upper_coef[3] / h6,
                                                                    upper_coef[4] / h6)),
                         # d7
                         DerivativeCoefficientRow{T, 1, 11}(SVector(-q1_7 / h7,
                                                                    -q2_7 / h7,
                                                                    -q3_7 / h7,
                                                                    -q4_7 / h7,
                                                                    -q5_7 / h7,
                                                                    -q6_7 / h7,
                                                                    T(0),
                                                                    q7_8 / h7,
                                                                    upper_coef[2] / h7,
                                                                    upper_coef[3] / h7,
                                                                    upper_coef[4] / h7)),
                         # d8
                         DerivativeCoefficientRow{T, 1, 12}(SVector(-q1_8 / h8,
                                                                    -q2_8 / h8,
                                                                    -q3_8 / h8,
                                                                    -q4_8 / h8,
                                                                    -q5_8 / h8,
                                                                    -q6_8 / h8,
                                                                    -q7_8 / h8,
                                                                    T(0),
                                                                    upper_coef[1] / h8,
                                                                    upper_coef[2] / h8,
                                                                    upper_coef[3] / h8,
                                                                    upper_coef[4] / h8)))
        right_boundary = .-left_boundary
        right_weights = left_weights
        left_boundary_derivatives = Tuple{}()
        right_boundary_derivatives = left_boundary_derivatives

        DerivativeCoefficients(left_boundary, right_boundary,
                               left_boundary_derivatives, right_boundary_derivatives,
                               lower_coef, central_coef, upper_coef,
                               left_weights, right_weights, mode, 1, order, source)
    elseif order == 10
        # interior stencil
        upper_coef = SVector(T(5 // 6), T(-5 // 21), T(5 // 84), T(-5 // 504), T(1 // 1260))
        central_coef = zero(T)
        lower_coef = -upper_coef

        # The diagonal norm `H` and the antisymmetric `Q` of the boundary
        # closure as printed in the paper, read as exact rational numbers.
        h1 = T(10000000000000 // 100000000000000)
        h2 = T(58980851260667 // 100000000000000)
        h3 = T(95666820955973 // 100000000000000)
        h4 = T(11500297411596 // 10000000000000)
        h5 = T(11232986993248 // 10000000000000)
        h6 = T(10123020150951 // 10000000000000)
        h7 = T(99877122702527 // 100000000000000)
        h8 = T(10000873322761 // 10000000000000)
        h9 = T(10000045540888 // 10000000000000)
        h10 = T(99999861455083 // 100000000000000)
        left_weights = SVector(h1, h2, h3, h4, h5, h6, h7, h8, h9, h10)

        q1_2 = T(67548747038002 // 100000000000000)
        q1_3 = T(-26691978151546 // 100000000000000)
        q1_4 = T(14438714982130 // 100000000000000)
        q1_5 = T(-77273673750760 // 1000000000000000)
        q1_6 = T(25570078343005 // 1000000000000000)
        q1_7 = T(42808774693299 // 10000000000000000)
        q1_8 = T(-82902108933389 // 10000000000000000)
        q1_9 = T(32031176427908 // 10000000000000000)
        q1_10 = T(-44502749689556 // 100000000000000000)
        q2_3 = T(95146052715180 // 100000000000000)
        q2_4 = T(-42442349882626 // 100000000000000)
        q2_5 = T(21538865145190 // 100000000000000)
        q2_6 = T(-71939778160350 // 1000000000000000)
        q2_7 = T(-82539187832840 // 10000000000000000)
        q2_8 = T(19930661669090 // 1000000000000000)
        q2_9 = T(-77433256989613 // 10000000000000000)
        q2_10 = T(10681515760869 // 10000000000000000)
        q3_4 = T(96073770842387 // 100000000000000)
        q3_5 = T(-39378595264609 // 100000000000000)
        q3_6 = T(13302097358959 // 100000000000000)
        q3_7 = T(81200458151489 // 1000000000000000000)
        q3_8 = T(-23849770528789 // 1000000000000000)
        q3_9 = T(96600442856829 // 10000000000000000)
        q3_10 = T(-13234579460680 // 10000000000000000)
        q4_5 = T(91551097634196 // 100000000000000)
        q4_6 = T(-28541713079648 // 100000000000000)
        q4_7 = T(41398809121293 // 1000000000000000)
        q4_8 = T(17256059167927 // 1000000000000000)
        q4_9 = T(-94349194803610 // 10000000000000000)
        q4_10 = T(13875650645663 // 10000000000000000)
        q5_6 = T(83519401865051 // 100000000000000)
        q5_7 = T(-20586492924974 // 100000000000000)
        q5_8 = T(31230261235901 // 1000000000000000)
        q5_9 = T(-20969453466651 // 100000000000000000)
        q5_10 = T(-50965470499782 // 100000000000000000)
        q6_7 = T(81046389580138 // 100000000000000)
        q6_8 = T(-21879194972141 // 100000000000000)
        q6_9 = T(52977237804899 // 1000000000000000)
        q6_10 = T(-90146730522360 // 10000000000000000)
        q7_8 = T(82787884456005 // 100000000000000)
        q7_9 = T(-23582460382545 // 100000000000000)
        q7_10 = T(59178678209520 // 1000000000000000)
        q8_9 = T(83301028859275 // 100000000000000)
        q8_10 = T(-23804321850015 // 100000000000000)
        q9_10 = T(83333655748509 // 100000000000000)

        # `D[i, :] = (Q[i, :] - δ₁ᵢ e₁ᵀ / 2) / H[i, i]`. The entries reaching
        # beyond the boundary closure are fixed by the antisymmetry of `Q`:
        # row `j` uses the interior stencil and `H[j, j] = 1` there, so
        # `Q[i, j] = -Q[j, i] = upper_coef[j - i]`.
        left_boundary = (
                         # d1
                         DerivativeCoefficientRow{T, 1, 10}(SVector(-T(1 // 2) / h1,
                                                                    q1_2 / h1,
                                                                    q1_3 / h1,
                                                                    q1_4 / h1,
                                                                    q1_5 / h1,
                                                                    q1_6 / h1,
                                                                    q1_7 / h1,
                                                                    q1_8 / h1,
                                                                    q1_9 / h1,
                                                                    q1_10 / h1)),
                         # d2
                         DerivativeCoefficientRow{T, 1, 10}(SVector(-q1_2 / h2,
                                                                    T(0),
                                                                    q2_3 / h2,
                                                                    q2_4 / h2,
                                                                    q2_5 / h2,
                                                                    q2_6 / h2,
                                                                    q2_7 / h2,
                                                                    q2_8 / h2,
                                                                    q2_9 / h2,
                                                                    q2_10 / h2)),
                         # d3
                         DerivativeCoefficientRow{T, 1, 10}(SVector(-q1_3 / h3,
                                                                    -q2_3 / h3,
                                                                    T(0),
                                                                    q3_4 / h3,
                                                                    q3_5 / h3,
                                                                    q3_6 / h3,
                                                                    q3_7 / h3,
                                                                    q3_8 / h3,
                                                                    q3_9 / h3,
                                                                    q3_10 / h3)),
                         # d4
                         DerivativeCoefficientRow{T, 1, 10}(SVector(-q1_4 / h4,
                                                                    -q2_4 / h4,
                                                                    -q3_4 / h4,
                                                                    T(0),
                                                                    q4_5 / h4,
                                                                    q4_6 / h4,
                                                                    q4_7 / h4,
                                                                    q4_8 / h4,
                                                                    q4_9 / h4,
                                                                    q4_10 / h4)),
                         # d5
                         DerivativeCoefficientRow{T, 1, 10}(SVector(-q1_5 / h5,
                                                                    -q2_5 / h5,
                                                                    -q3_5 / h5,
                                                                    -q4_5 / h5,
                                                                    T(0),
                                                                    q5_6 / h5,
                                                                    q5_7 / h5,
                                                                    q5_8 / h5,
                                                                    q5_9 / h5,
                                                                    q5_10 / h5)),
                         # d6
                         DerivativeCoefficientRow{T, 1, 11}(SVector(-q1_6 / h6,
                                                                    -q2_6 / h6,
                                                                    -q3_6 / h6,
                                                                    -q4_6 / h6,
                                                                    -q5_6 / h6,
                                                                    T(0),
                                                                    q6_7 / h6,
                                                                    q6_8 / h6,
                                                                    q6_9 / h6,
                                                                    q6_10 / h6,
                                                                    upper_coef[5] / h6)),
                         # d7
                         DerivativeCoefficientRow{T, 1, 12}(SVector(-q1_7 / h7,
                                                                    -q2_7 / h7,
                                                                    -q3_7 / h7,
                                                                    -q4_7 / h7,
                                                                    -q5_7 / h7,
                                                                    -q6_7 / h7,
                                                                    T(0),
                                                                    q7_8 / h7,
                                                                    q7_9 / h7,
                                                                    q7_10 / h7,
                                                                    upper_coef[4] / h7,
                                                                    upper_coef[5] / h7)),
                         # d8
                         DerivativeCoefficientRow{T, 1, 13}(SVector(-q1_8 / h8,
                                                                    -q2_8 / h8,
                                                                    -q3_8 / h8,
                                                                    -q4_8 / h8,
                                                                    -q5_8 / h8,
                                                                    -q6_8 / h8,
                                                                    -q7_8 / h8,
                                                                    T(0),
                                                                    q8_9 / h8,
                                                                    q8_10 / h8,
                                                                    upper_coef[3] / h8,
                                                                    upper_coef[4] / h8,
                                                                    upper_coef[5] / h8)),
                         # d9
                         DerivativeCoefficientRow{T, 1, 14}(SVector(-q1_9 / h9,
                                                                    -q2_9 / h9,
                                                                    -q3_9 / h9,
                                                                    -q4_9 / h9,
                                                                    -q5_9 / h9,
                                                                    -q6_9 / h9,
                                                                    -q7_9 / h9,
                                                                    -q8_9 / h9,
                                                                    T(0),
                                                                    q9_10 / h9,
                                                                    upper_coef[2] / h9,
                                                                    upper_coef[3] / h9,
                                                                    upper_coef[4] / h9,
                                                                    upper_coef[5] / h9)),
                         # d10
                         DerivativeCoefficientRow{T, 1, 15}(SVector(-q1_10 / h10,
                                                                    -q2_10 / h10,
                                                                    -q3_10 / h10,
                                                                    -q4_10 / h10,
                                                                    -q5_10 / h10,
                                                                    -q6_10 / h10,
                                                                    -q7_10 / h10,
                                                                    -q8_10 / h10,
                                                                    -q9_10 / h10,
                                                                    T(0),
                                                                    upper_coef[1] / h10,
                                                                    upper_coef[2] / h10,
                                                                    upper_coef[3] / h10,
                                                                    upper_coef[4] / h10,
                                                                    upper_coef[5] / h10)))
        right_boundary = .-left_boundary
        right_weights = left_weights
        left_boundary_derivatives = Tuple{}()
        right_boundary_derivatives = left_boundary_derivatives

        DerivativeCoefficients(left_boundary, right_boundary,
                               left_boundary_derivatives, right_boundary_derivatives,
                               lower_coef, central_coef, upper_coef,
                               left_weights, right_weights, mode, 1, order, source)
    elseif order == 12
        # interior stencil
        upper_coef = SVector(T(6 // 7), T(-15 // 56), T(5 // 63), T(-1 // 56), T(1 // 385),
                             T(-1 // 5544))
        central_coef = zero(T)
        lower_coef = -upper_coef

        # The diagonal norm `H` and the antisymmetric `Q` of the boundary
        # closure as printed in the paper, read as exact rational numbers.
        h1 = T(10000000000011 // 100000000000000)
        h2 = T(59616216757547 // 100000000000000)
        h3 = T(99065699844442 // 100000000000000)
        h4 = T(12512548713913 // 10000000000000)
        h5 = T(13316678989403 // 10000000000000)
        h6 = T(12093375037721 // 10000000000000)
        h7 = T(10236491595704 // 10000000000000)
        h8 = T(99685258909811 // 100000000000000)
        h9 = T(10004766563923 // 10000000000000)
        h10 = T(99993617879146 // 100000000000000)
        h11 = T(10000063122914 // 10000000000000)
        h12 = T(99999966373260 // 100000000000000)
        left_weights = SVector(h1, h2, h3, h4, h5, h6, h7, h8, h9, h10, h11, h12)

        q1_2 = T(67597560728423 // 100000000000000)
        q1_3 = T(-26859785384416 // 100000000000000)
        q1_4 = T(14850302678903 // 100000000000000)
        q1_5 = T(-87976689586154 // 1000000000000000)
        q1_6 = T(41833336322613 // 1000000000000000)
        q1_7 = T(-22216684976993 // 10000000000000000)
        q1_8 = T(-15910034062022 // 1000000000000000)
        q1_9 = T(11296706376589 // 1000000000000000)
        q1_10 = T(-31823678285130 // 10000000000000000)
        q1_11 = T(24843594063649 // 100000000000000000)
        q1_12 = T(31501105449828 // 1000000000000000000)
        q2_3 = T(95424013647146 // 100000000000000)
        q2_4 = T(-43389334603464 // 100000000000000)
        q2_5 = T(24285669347653 // 100000000000000)
        q2_6 = T(-11443465137214 // 100000000000000)
        q2_7 = T(85942765682435 // 10000000000000000)
        q2_8 = T(40290424215772 // 1000000000000000)
        q2_9 = T(-29396383714543 // 1000000000000000)
        q2_10 = T(85601827834256 // 10000000000000000)
        q2_11 = T(-78128092862319 // 100000000000000000)
        q2_12 = T(-60444181254875 // 1000000000000000000)
        q3_4 = T(97065114311923 // 100000000000000)
        q3_5 = T(-43205328628292 // 100000000000000)
        q3_6 = T(19549970932735 // 100000000000000)
        q3_7 = T(-24406885385172 // 1000000000000000)
        q3_8 = T(-55737279079895 // 1000000000000000)
        q3_9 = T(43772338637753 // 1000000000000000)
        q3_10 = T(-13727655130726 // 1000000000000000)
        q3_11 = T(16271304373071 // 10000000000000000)
        q3_12 = T(17066984372933 // 1000000000000000000)
        q4_5 = T(95375878629204 // 100000000000000)
        q4_6 = T(-36113954384951 // 100000000000000)
        q4_7 = T(69749289223875 // 1000000000000000)
        q4_8 = T(65161366516465 // 1000000000000000)
        q4_9 = T(-60325702283960 // 1000000000000000)
        q4_10 = T(21188913621662 // 1000000000000000)
        q4_11 = T(-32632650250470 // 10000000000000000)
        q4_12 = T(13097937809499 // 100000000000000000)
        q5_6 = T(88676146394834 // 100000000000000)
        q5_7 = T(-21292503103800 // 100000000000000)
        q5_8 = T(-46037018833218 // 1000000000000000)
        q5_9 = T(74338719466734 // 1000000000000000)
        q5_10 = T(-31217656663809 // 1000000000000000)
        q5_11 = T(61239492854797 // 10000000000000000)
        q5_12 = T(-45892226603067 // 100000000000000000)
        q6_7 = T(77461223007026 // 100000000000000)
        q6_8 = T(-10609547334165 // 100000000000000)
        q6_9 = T(-44853791547749 // 1000000000000000)
        q6_10 = T(32436468405486 // 1000000000000000)
        q6_11 = T(-84387621360184 // 10000000000000000)
        q6_12 = T(85964292632428 // 100000000000000000)
        q7_8 = T(74758103262966 // 100000000000000)
        q7_9 = T(-15730779067906 // 100000000000000)
        q7_10 = T(26517620342970 // 1000000000000000)
        q7_11 = T(-43175367549700 // 10000000000000000)
        q7_12 = T(11092605832824 // 10000000000000000)
        q8_9 = T(80975719267918 // 100000000000000)
        q8_10 = T(-23568822398349 // 100000000000000)
        q8_11 = T(69373143801571 // 1000000000000000)
        q8_12 = T(-16606121869177 // 1000000000000000)
        q9_10 = T(84765775072084 // 100000000000000)
        q9_11 = T(-26369594097148 // 100000000000000)
        q9_12 = T(78759594625702 // 1000000000000000)
        q10_11 = T(85631774953989 // 100000000000000)
        q10_12 = T(-26769768119702 // 100000000000000)
        q11_12 = T(85712580212095 // 100000000000000)

        # `D[i, :] = (Q[i, :] - δ₁ᵢ e₁ᵀ / 2) / H[i, i]`. The entries reaching
        # beyond the boundary closure are fixed by the antisymmetry of `Q`:
        # row `j` uses the interior stencil and `H[j, j] = 1` there, so
        # `Q[i, j] = -Q[j, i] = upper_coef[j - i]`.
        left_boundary = (
                         # d1
                         DerivativeCoefficientRow{T, 1, 12}(SVector(-T(1 // 2) / h1,
                                                                    q1_2 / h1,
                                                                    q1_3 / h1,
                                                                    q1_4 / h1,
                                                                    q1_5 / h1,
                                                                    q1_6 / h1,
                                                                    q1_7 / h1,
                                                                    q1_8 / h1,
                                                                    q1_9 / h1,
                                                                    q1_10 / h1,
                                                                    q1_11 / h1,
                                                                    q1_12 / h1)),
                         # d2
                         DerivativeCoefficientRow{T, 1, 12}(SVector(-q1_2 / h2,
                                                                    T(0),
                                                                    q2_3 / h2,
                                                                    q2_4 / h2,
                                                                    q2_5 / h2,
                                                                    q2_6 / h2,
                                                                    q2_7 / h2,
                                                                    q2_8 / h2,
                                                                    q2_9 / h2,
                                                                    q2_10 / h2,
                                                                    q2_11 / h2,
                                                                    q2_12 / h2)),
                         # d3
                         DerivativeCoefficientRow{T, 1, 12}(SVector(-q1_3 / h3,
                                                                    -q2_3 / h3,
                                                                    T(0),
                                                                    q3_4 / h3,
                                                                    q3_5 / h3,
                                                                    q3_6 / h3,
                                                                    q3_7 / h3,
                                                                    q3_8 / h3,
                                                                    q3_9 / h3,
                                                                    q3_10 / h3,
                                                                    q3_11 / h3,
                                                                    q3_12 / h3)),
                         # d4
                         DerivativeCoefficientRow{T, 1, 12}(SVector(-q1_4 / h4,
                                                                    -q2_4 / h4,
                                                                    -q3_4 / h4,
                                                                    T(0),
                                                                    q4_5 / h4,
                                                                    q4_6 / h4,
                                                                    q4_7 / h4,
                                                                    q4_8 / h4,
                                                                    q4_9 / h4,
                                                                    q4_10 / h4,
                                                                    q4_11 / h4,
                                                                    q4_12 / h4)),
                         # d5
                         DerivativeCoefficientRow{T, 1, 12}(SVector(-q1_5 / h5,
                                                                    -q2_5 / h5,
                                                                    -q3_5 / h5,
                                                                    -q4_5 / h5,
                                                                    T(0),
                                                                    q5_6 / h5,
                                                                    q5_7 / h5,
                                                                    q5_8 / h5,
                                                                    q5_9 / h5,
                                                                    q5_10 / h5,
                                                                    q5_11 / h5,
                                                                    q5_12 / h5)),
                         # d6
                         DerivativeCoefficientRow{T, 1, 12}(SVector(-q1_6 / h6,
                                                                    -q2_6 / h6,
                                                                    -q3_6 / h6,
                                                                    -q4_6 / h6,
                                                                    -q5_6 / h6,
                                                                    T(0),
                                                                    q6_7 / h6,
                                                                    q6_8 / h6,
                                                                    q6_9 / h6,
                                                                    q6_10 / h6,
                                                                    q6_11 / h6,
                                                                    q6_12 / h6)),
                         # d7
                         DerivativeCoefficientRow{T, 1, 13}(SVector(-q1_7 / h7,
                                                                    -q2_7 / h7,
                                                                    -q3_7 / h7,
                                                                    -q4_7 / h7,
                                                                    -q5_7 / h7,
                                                                    -q6_7 / h7,
                                                                    T(0),
                                                                    q7_8 / h7,
                                                                    q7_9 / h7,
                                                                    q7_10 / h7,
                                                                    q7_11 / h7,
                                                                    q7_12 / h7,
                                                                    upper_coef[6] / h7)),
                         # d8
                         DerivativeCoefficientRow{T, 1, 14}(SVector(-q1_8 / h8,
                                                                    -q2_8 / h8,
                                                                    -q3_8 / h8,
                                                                    -q4_8 / h8,
                                                                    -q5_8 / h8,
                                                                    -q6_8 / h8,
                                                                    -q7_8 / h8,
                                                                    T(0),
                                                                    q8_9 / h8,
                                                                    q8_10 / h8,
                                                                    q8_11 / h8,
                                                                    q8_12 / h8,
                                                                    upper_coef[5] / h8,
                                                                    upper_coef[6] / h8)),
                         # d9
                         DerivativeCoefficientRow{T, 1, 15}(SVector(-q1_9 / h9,
                                                                    -q2_9 / h9,
                                                                    -q3_9 / h9,
                                                                    -q4_9 / h9,
                                                                    -q5_9 / h9,
                                                                    -q6_9 / h9,
                                                                    -q7_9 / h9,
                                                                    -q8_9 / h9,
                                                                    T(0),
                                                                    q9_10 / h9,
                                                                    q9_11 / h9,
                                                                    q9_12 / h9,
                                                                    upper_coef[4] / h9,
                                                                    upper_coef[5] / h9,
                                                                    upper_coef[6] / h9)),
                         # d10
                         DerivativeCoefficientRow{T, 1, 16}(SVector(-q1_10 / h10,
                                                                    -q2_10 / h10,
                                                                    -q3_10 / h10,
                                                                    -q4_10 / h10,
                                                                    -q5_10 / h10,
                                                                    -q6_10 / h10,
                                                                    -q7_10 / h10,
                                                                    -q8_10 / h10,
                                                                    -q9_10 / h10,
                                                                    T(0),
                                                                    q10_11 / h10,
                                                                    q10_12 / h10,
                                                                    upper_coef[3] / h10,
                                                                    upper_coef[4] / h10,
                                                                    upper_coef[5] / h10,
                                                                    upper_coef[6] / h10)),
                         # d11
                         DerivativeCoefficientRow{T, 1, 17}(SVector(-q1_11 / h11,
                                                                    -q2_11 / h11,
                                                                    -q3_11 / h11,
                                                                    -q4_11 / h11,
                                                                    -q5_11 / h11,
                                                                    -q6_11 / h11,
                                                                    -q7_11 / h11,
                                                                    -q8_11 / h11,
                                                                    -q9_11 / h11,
                                                                    -q10_11 / h11,
                                                                    T(0),
                                                                    q11_12 / h11,
                                                                    upper_coef[2] / h11,
                                                                    upper_coef[3] / h11,
                                                                    upper_coef[4] / h11,
                                                                    upper_coef[5] / h11,
                                                                    upper_coef[6] / h11)),
                         # d12
                         DerivativeCoefficientRow{T, 1, 18}(SVector(-q1_12 / h12,
                                                                    -q2_12 / h12,
                                                                    -q3_12 / h12,
                                                                    -q4_12 / h12,
                                                                    -q5_12 / h12,
                                                                    -q6_12 / h12,
                                                                    -q7_12 / h12,
                                                                    -q8_12 / h12,
                                                                    -q9_12 / h12,
                                                                    -q10_12 / h12,
                                                                    -q11_12 / h12,
                                                                    T(0),
                                                                    upper_coef[1] / h12,
                                                                    upper_coef[2] / h12,
                                                                    upper_coef[3] / h12,
                                                                    upper_coef[4] / h12,
                                                                    upper_coef[5] / h12,
                                                                    upper_coef[6] / h12)))
        right_boundary = .-left_boundary
        right_weights = left_weights
        left_boundary_derivatives = Tuple{}()
        right_boundary_derivatives = left_boundary_derivatives

        DerivativeCoefficients(left_boundary, right_boundary,
                               left_boundary_derivatives, right_boundary_derivatives,
                               lower_coef, central_coef, upper_coef,
                               left_weights, right_weights, mode, 1, order, source)
    else
        throw(ArgumentError("Order $order not implemented/derived."))
    end
end
