
"""
    MattssonAlmquistVanDerWeide2018Minimal()

Coefficients of the optimized SBP operators with nonuniform grid given in
- Mattsson, Almquist, van der Weide (2018)
  Boundary optimized diagonal-norm SBP operators.
  Journal of Computational Physics 374, pp. 1261-1266.
"""
struct MattssonAlmquistVanDerWeide2018Minimal <: SourceOfCoefficients end

function Base.show(io::IO, source::MattssonAlmquistVanDerWeide2018Minimal)
    if get(io, :compact, false)
        summary(io, source)
    else
        print(io,
              "Mattsson, Almquist, van der Weide (2018) \n",
              "  Boundary optimized diagonal-norm SBP operators ('Minimal'). \n",
              "  Journal of Computational Physics 374, pp. 1261-1266.")
    end
end

struct BoundaryAdaptedGrid{T, M, Grid} <: AbstractArray{T, 1}
    xmin::T
    xmax::T
    xstart::SVector{M, T}
    uniform_grid::Grid
    Δx::T
end

function BoundaryAdaptedGrid(xmin::T, xmax::T, _xstart::SVector{M, T}, N::Int) where {M, T}
    @argcheck xmin < xmax
    @argcheck N > 2M

    Δx = (xmax - xmin) / (2 * _xstart[end] + N + 1 - 2M)
    xstart = Δx .* _xstart
    if N - 2M == 1 # This is to avoid an error if starting and end points are not the same due to rounding errors
        uniform_grid = range(xmax - xstart[end] - Δx, xmax - xstart[end] - Δx, length = 1)
    else
        uniform_grid = range(xmin + xstart[end] + Δx, xmax - xstart[end] - Δx,
                             length = N - 2M)
    end
    BoundaryAdaptedGrid{T, M, typeof(uniform_grid)}(xmin, xmax, xstart, uniform_grid, Δx)
end

function BoundaryAdaptedGrid(xmin, xmax, xstart, N)
    T = promote_type(typeof(xmin), typeof(xmax), eltype(xstart))
    BoundaryAdaptedGrid(T(xmin), T(xmax), T.(xstart), N)
end

function Base.length(grid::BoundaryAdaptedGrid)
    length(grid.uniform_grid) + 2 * length(grid.xstart)
end

function Base.getindex(grid::BoundaryAdaptedGrid, i::Int)
    N = length(grid)
    M = length(grid.xstart)
    @boundscheck begin
        @argcheck i > 0
        @argcheck i <= N
    end

    if i <= M
        grid.xmin + grid.xstart[i]
    elseif i >= N - M + 1
        grid.xmax - grid.xstart[1 + N - i]
    else
        @inbounds x = getindex(grid.uniform_grid, i - M)
        x
    end
end

Base.size(grid::BoundaryAdaptedGrid) = (length(grid),)
Base.step(grid::BoundaryAdaptedGrid) = grid.Δx

function construct_grid(::MattssonAlmquistVanDerWeide2018Minimal, accuracy_order, xmin,
                        xmax, N)
    @argcheck N > 6
    T = promote_type(typeof(xmin), typeof(xmax))

    # `xstart` contains only the non-uniform grid points 0, ξ₁, ..., ξₙ of the
    # reference, measured in units of the interior grid spacing. The equispaced
    # points following them are generated by `BoundaryAdaptedGrid`. Listing
    # them here as well would yield the same grid but increase the minimal
    # number of nodes required to construct the operator.
    if accuracy_order == 4
        xstart = SVector(T(0.0000000000000e+00),
                         T(7.7122987842562e-01))
    elseif accuracy_order == 6
        xstart = SVector(T(0.0000000000000e+00),
                         T(4.0842950991998e-01),
                         T(1.1968523189207e+00))
    elseif accuracy_order == 8
        xstart = SVector(T(0.0000000000000e+00),
                         T(4.9439570885261e-01),
                         T(1.4051531374839e+00))
    elseif accuracy_order == 10
        xstart = SVector(T(0.0000000000000e+00),
                         T(5.8556160757529e-01),
                         T(1.7473267488572e+00),
                         T(3.0000000000000e+00))
    elseif accuracy_order == 12
        xstart = SVector(T(0.0000000000000e+00),
                         T(4.6552112904489e-01),
                         T(1.4647984306493e+00),
                         T(2.7620429464763e+00),
                         T(4.0000000000000e+00))
    else
        throw(ArgumentError("Accuracy order $accuracy_order not implemented/derived."))
    end

    BoundaryAdaptedGrid(xmin, xmax, xstart, N)
end

function first_derivative_coefficients(source::MattssonAlmquistVanDerWeide2018Minimal,
                                       order::Int, T = Float64, mode = FastMode())
    if order == 4
        # interior stencil
        upper_coef = SVector(T(2 // 3), T(-1 // 12))
        central_coef = zero(T)
        lower_coef = -upper_coef

        # The diagonal norm `H` and the antisymmetric `Q` of the boundary
        # closure as printed in the paper, read as exact rational numbers.
        h1 = T(26864248295847 // 100000000000000)
        h2 = T(10094667153500 // 10000000000000)
        h3 = T(99312068011715 // 100000000000000)
        left_weights = SVector(h1, h2, h3)

        q1_2 = T(61697245625434 // 100000000000000)
        q1_3 = T(-11697245625434 // 100000000000000)
        q2_3 = T(70030578958767 // 100000000000000)

        # `D[i, :] = (Q[i, :] - δ₁ᵢ e₁ᵀ / 2) / H[i, i]`. The entries reaching
        # into the uniform part of the grid are fixed by the interior stencil,
        # `Q[i, j] = upper_coef[j - i]`, since `H[j, j] = 1` there.
        left_boundary = (
                         # d1
                         DerivativeCoefficientRow{T, 1, 3}(SVector(-T(1 // 2) / h1,
                                                                   q1_2 / h1,
                                                                   q1_3 / h1)),
                         # d2
                         DerivativeCoefficientRow{T, 1, 4}(SVector(-q1_2 / h2,
                                                                   T(0),
                                                                   q2_3 / h2,
                                                                   upper_coef[2] / h2)),
                         # d3
                         DerivativeCoefficientRow{T, 1, 5}(SVector(-q1_3 / h3,
                                                                   -q2_3 / h3,
                                                                   T(0),
                                                                   upper_coef[1] / h3,
                                                                   upper_coef[2] / h3)))
        right_boundary = .-left_boundary
        right_weights = left_weights
        left_boundary_derivatives = Tuple{}()
        right_boundary_derivatives = left_boundary_derivatives

        DerivativeCoefficients(left_boundary, right_boundary,
                               left_boundary_derivatives, right_boundary_derivatives,
                               lower_coef, central_coef, upper_coef,
                               left_weights, right_weights, mode, 1, order, source)
    elseif order == 6
        # interior stencil
        upper_coef = SVector(T(3 // 4), T(-3 // 20), T(1 // 60))
        central_coef = zero(T)
        lower_coef = -upper_coef

        # The diagonal norm `H` and the antisymmetric `Q` of the boundary
        # closure as printed in the paper, read as exact rational numbers.
        h1 = T(12740260779883 // 100000000000000)
        h2 = T(61820981002054 // 100000000000000)
        h3 = T(94308973897679 // 100000000000000)
        h4 = T(10093019060199 // 10000000000000)
        h5 = T(99884825610465 // 100000000000000)
        left_weights = SVector(h1, h2, h3, h4, h5)

        q1_2 = T(63217364546846 // 100000000000000)
        q1_3 = T(-16411963429825 // 100000000000000)
        q1_4 = T(36495407984639 // 1000000000000000)
        q1_5 = T(-45494191548490 // 10000000000000000)
        q2_3 = T(80515625504417 // 100000000000000)
        q2_4 = T(-20755653563249 // 100000000000000)
        q2_5 = T(34573926056780 // 1000000000000000)
        q3_4 = T(79402676057785 // 100000000000000)
        q3_5 = T(-16965680649860 // 100000000000000)
        q4_5 = T(75629896626333 // 100000000000000)

        # `D[i, :] = (Q[i, :] - δ₁ᵢ e₁ᵀ / 2) / H[i, i]`. The entries reaching
        # into the uniform part of the grid are fixed by the interior stencil,
        # `Q[i, j] = upper_coef[j - i]`, since `H[j, j] = 1` there.
        left_boundary = (
                         # d1
                         DerivativeCoefficientRow{T, 1, 5}(SVector(-T(1 // 2) / h1,
                                                                   q1_2 / h1,
                                                                   q1_3 / h1,
                                                                   q1_4 / h1,
                                                                   q1_5 / h1)),
                         # d2
                         DerivativeCoefficientRow{T, 1, 5}(SVector(-q1_2 / h2,
                                                                   T(0),
                                                                   q2_3 / h2,
                                                                   q2_4 / h2,
                                                                   q2_5 / h2)),
                         # d3
                         DerivativeCoefficientRow{T, 1, 6}(SVector(-q1_3 / h3,
                                                                   -q2_3 / h3,
                                                                   T(0),
                                                                   q3_4 / h3,
                                                                   q3_5 / h3,
                                                                   upper_coef[3] / h3)),
                         # d4
                         DerivativeCoefficientRow{T, 1, 7}(SVector(-q1_4 / h4,
                                                                   -q2_4 / h4,
                                                                   -q3_4 / h4,
                                                                   T(0),
                                                                   q4_5 / h4,
                                                                   upper_coef[2] / h4,
                                                                   upper_coef[3] / h4)),
                         # d5
                         DerivativeCoefficientRow{T, 1, 8}(SVector(-q1_5 / h5,
                                                                   -q2_5 / h5,
                                                                   -q3_5 / h5,
                                                                   -q4_5 / h5,
                                                                   T(0),
                                                                   upper_coef[1] / h5,
                                                                   upper_coef[2] / h5,
                                                                   upper_coef[3] / h5)))
        right_boundary = .-left_boundary
        right_weights = left_weights
        left_boundary_derivatives = Tuple{}()
        right_boundary_derivatives = left_boundary_derivatives

        DerivativeCoefficients(left_boundary, right_boundary,
                               left_boundary_derivatives, right_boundary_derivatives,
                               lower_coef, central_coef, upper_coef,
                               left_weights, right_weights, mode, 1, order, source)
    elseif order == 8
        # interior stencil
        upper_coef = SVector(T(4 // 5), T(-1 // 5), T(4 // 105), T(-1 // 280))
        central_coef = zero(T)
        lower_coef = -upper_coef

        # The diagonal norm `H` and the antisymmetric `Q` of the boundary
        # closure as printed in the paper, read as exact rational numbers.
        h1 = T(14523997892351 // 100000000000000)
        h2 = T(76864793350174 // 100000000000000)
        h3 = T(99116487068535 // 100000000000000)
        h4 = T(99992473335107 // 100000000000000)
        h5 = T(10002097054636 // 10000000000000)
        h6 = T(99996591555866 // 100000000000000)
        left_weights = SVector(h1, h2, h3, h4, h5, h6)

        q1_2 = T(66697342753834 // 100000000000000)
        q1_3 = T(-22919342278749 // 100000000000000)
        q1_4 = T(74283116457276 // 1000000000000000)
        q1_5 = T(-12020661178873 // 1000000000000000)
        q1_6 = T(-42460029252999 // 1000000000000000000)
        q2_3 = T(88241196934163 // 100000000000000)
        q2_4 = T(-26653314104602 // 100000000000000)
        q2_5 = T(55302527504316 // 1000000000000000)
        q2_6 = T(-42079282615860 // 10000000000000000)
        q3_4 = T(82904844081126 // 100000000000000)
        q3_5 = T(-21156614214635 // 100000000000000)
        q3_6 = T(39307676460659 // 1000000000000000)
        q4_5 = T(80305501223679 // 100000000000000)
        q4_6 = T(-20078040553808 // 100000000000000)
        q5_6 = T(80024692689207 // 100000000000000)

        # `D[i, :] = (Q[i, :] - δ₁ᵢ e₁ᵀ / 2) / H[i, i]`. The entries reaching
        # into the uniform part of the grid are fixed by the interior stencil,
        # `Q[i, j] = upper_coef[j - i]`, since `H[j, j] = 1` there.
        left_boundary = (
                         # d1
                         DerivativeCoefficientRow{T, 1, 6}(SVector(-T(1 // 2) / h1,
                                                                   q1_2 / h1,
                                                                   q1_3 / h1,
                                                                   q1_4 / h1,
                                                                   q1_5 / h1,
                                                                   q1_6 / h1)),
                         # d2
                         DerivativeCoefficientRow{T, 1, 6}(SVector(-q1_2 / h2,
                                                                   T(0),
                                                                   q2_3 / h2,
                                                                   q2_4 / h2,
                                                                   q2_5 / h2,
                                                                   q2_6 / h2)),
                         # d3
                         DerivativeCoefficientRow{T, 1, 7}(SVector(-q1_3 / h3,
                                                                   -q2_3 / h3,
                                                                   T(0),
                                                                   q3_4 / h3,
                                                                   q3_5 / h3,
                                                                   q3_6 / h3,
                                                                   upper_coef[4] / h3)),
                         # d4
                         DerivativeCoefficientRow{T, 1, 8}(SVector(-q1_4 / h4,
                                                                   -q2_4 / h4,
                                                                   -q3_4 / h4,
                                                                   T(0),
                                                                   q4_5 / h4,
                                                                   q4_6 / h4,
                                                                   upper_coef[3] / h4,
                                                                   upper_coef[4] / h4)),
                         # d5
                         DerivativeCoefficientRow{T, 1, 9}(SVector(-q1_5 / h5,
                                                                   -q2_5 / h5,
                                                                   -q3_5 / h5,
                                                                   -q4_5 / h5,
                                                                   T(0),
                                                                   q5_6 / h5,
                                                                   upper_coef[2] / h5,
                                                                   upper_coef[3] / h5,
                                                                   upper_coef[4] / h5)),
                         # d6
                         DerivativeCoefficientRow{T, 1, 10}(SVector(-q1_6 / h6,
                                                                    -q2_6 / h6,
                                                                    -q3_6 / h6,
                                                                    -q4_6 / h6,
                                                                    -q5_6 / h6,
                                                                    T(0),
                                                                    upper_coef[1] / h6,
                                                                    upper_coef[2] / h6,
                                                                    upper_coef[3] / h6,
                                                                    upper_coef[4] / h6)))
        right_boundary = .-left_boundary
        right_weights = left_weights
        left_boundary_derivatives = Tuple{}()
        right_boundary_derivatives = left_boundary_derivatives

        DerivativeCoefficients(left_boundary, right_boundary,
                               left_boundary_derivatives, right_boundary_derivatives,
                               lower_coef, central_coef, upper_coef,
                               left_weights, right_weights, mode, 1, order, source)
    elseif order == 10
        # interior stencil
        upper_coef = SVector(T(5 // 6), T(-5 // 21), T(5 // 84), T(-5 // 504), T(1 // 1260))
        central_coef = zero(T)
        lower_coef = -upper_coef

        # The diagonal norm `H` and the antisymmetric `Q` of the boundary
        # closure as printed in the paper, read as exact rational numbers.
        h1 = T(16717213975289 // 100000000000000)
        h2 = T(93675739171278 // 100000000000000)
        h3 = T(13035532379753 // 10000000000000)
        h4 = T(11188461804303 // 10000000000000)
        h5 = T(96664345922660 // 100000000000000)
        h6 = T(10083235564392 // 10000000000000)
        h7 = T(99858767377362 // 100000000000000)
        h8 = T(10001163606893 // 10000000000000)
        left_weights = SVector(h1, h2, h3, h4, h5, h6, h7, h8)

        q1_2 = T(67349296966214 // 100000000000000)
        q1_3 = T(-25186401896559 // 100000000000000)
        q1_4 = T(83431385420901 // 1000000000000000)
        q1_5 = T(25480326895984 // 1000000000000000)
        q1_6 = T(-45992420658252 // 1000000000000000)
        q1_7 = T(17526412909003 // 1000000000000000)
        q1_8 = T(-20746552641799 // 10000000000000000)
        q2_3 = T(91982892384044 // 100000000000000)
        q2_4 = T(-27262271754043 // 100000000000000)
        q2_5 = T(-50992113348238 // 1000000000000000)
        q2_6 = T(11814647281129 // 100000000000000)
        q2_7 = T(-46693123378079 // 1000000000000000)
        q2_8 = T(58255272771571 // 10000000000000000)
        q3_4 = T(78566746772741 // 100000000000000)
        q3_5 = T(-24097806629929 // 1000000000000000)
        q3_6 = T(-15312168858669 // 100000000000000)
        q3_7 = T(69451518963875 // 1000000000000000)
        q3_8 = T(-99345865998262 // 10000000000000000)
        q4_5 = T(62047871210535 // 100000000000000)
        q4_6 = T(14776775176509 // 1000000000000000)
        q4_7 = T(-46889652372990 // 1000000000000000)
        q4_8 = T(73166499053672 // 10000000000000000)
        q5_6 = T(69425006383507 // 100000000000000)
        q5_7 = T(-15686345740485 // 100000000000000)
        q5_8 = T(42609496719925 // 1000000000000000)
        q6_7 = T(80719535654891 // 100000000000000)
        q6_8 = T(-22953297936781 // 100000000000000)
        q7_8 = T(83142546796428 // 100000000000000)

        # `D[i, :] = (Q[i, :] - δ₁ᵢ e₁ᵀ / 2) / H[i, i]`. The entries reaching
        # into the uniform part of the grid are fixed by the interior stencil,
        # `Q[i, j] = upper_coef[j - i]`, since `H[j, j] = 1` there.
        left_boundary = (
                         # d1
                         DerivativeCoefficientRow{T, 1, 8}(SVector(-T(1 // 2) / h1,
                                                                   q1_2 / h1,
                                                                   q1_3 / h1,
                                                                   q1_4 / h1,
                                                                   q1_5 / h1,
                                                                   q1_6 / h1,
                                                                   q1_7 / h1,
                                                                   q1_8 / h1)),
                         # d2
                         DerivativeCoefficientRow{T, 1, 8}(SVector(-q1_2 / h2,
                                                                   T(0),
                                                                   q2_3 / h2,
                                                                   q2_4 / h2,
                                                                   q2_5 / h2,
                                                                   q2_6 / h2,
                                                                   q2_7 / h2,
                                                                   q2_8 / h2)),
                         # d3
                         DerivativeCoefficientRow{T, 1, 8}(SVector(-q1_3 / h3,
                                                                   -q2_3 / h3,
                                                                   T(0),
                                                                   q3_4 / h3,
                                                                   q3_5 / h3,
                                                                   q3_6 / h3,
                                                                   q3_7 / h3,
                                                                   q3_8 / h3)),
                         # d4
                         DerivativeCoefficientRow{T, 1, 9}(SVector(-q1_4 / h4,
                                                                   -q2_4 / h4,
                                                                   -q3_4 / h4,
                                                                   T(0),
                                                                   q4_5 / h4,
                                                                   q4_6 / h4,
                                                                   q4_7 / h4,
                                                                   q4_8 / h4,
                                                                   upper_coef[5] / h4)),
                         # d5
                         DerivativeCoefficientRow{T, 1, 10}(SVector(-q1_5 / h5,
                                                                    -q2_5 / h5,
                                                                    -q3_5 / h5,
                                                                    -q4_5 / h5,
                                                                    T(0),
                                                                    q5_6 / h5,
                                                                    q5_7 / h5,
                                                                    q5_8 / h5,
                                                                    upper_coef[4] / h5,
                                                                    upper_coef[5] / h5)),
                         # d6
                         DerivativeCoefficientRow{T, 1, 11}(SVector(-q1_6 / h6,
                                                                    -q2_6 / h6,
                                                                    -q3_6 / h6,
                                                                    -q4_6 / h6,
                                                                    -q5_6 / h6,
                                                                    T(0),
                                                                    q6_7 / h6,
                                                                    q6_8 / h6,
                                                                    upper_coef[3] / h6,
                                                                    upper_coef[4] / h6,
                                                                    upper_coef[5] / h6)),
                         # d7
                         DerivativeCoefficientRow{T, 1, 12}(SVector(-q1_7 / h7,
                                                                    -q2_7 / h7,
                                                                    -q3_7 / h7,
                                                                    -q4_7 / h7,
                                                                    -q5_7 / h7,
                                                                    -q6_7 / h7,
                                                                    T(0),
                                                                    q7_8 / h7,
                                                                    upper_coef[2] / h7,
                                                                    upper_coef[3] / h7,
                                                                    upper_coef[4] / h7,
                                                                    upper_coef[5] / h7)),
                         # d8
                         DerivativeCoefficientRow{T, 1, 13}(SVector(-q1_8 / h8,
                                                                    -q2_8 / h8,
                                                                    -q3_8 / h8,
                                                                    -q4_8 / h8,
                                                                    -q5_8 / h8,
                                                                    -q6_8 / h8,
                                                                    -q7_8 / h8,
                                                                    T(0),
                                                                    upper_coef[1] / h8,
                                                                    upper_coef[2] / h8,
                                                                    upper_coef[3] / h8,
                                                                    upper_coef[4] / h8,
                                                                    upper_coef[5] / h8)))
        right_boundary = .-left_boundary
        right_weights = left_weights
        left_boundary_derivatives = Tuple{}()
        right_boundary_derivatives = left_boundary_derivatives

        DerivativeCoefficients(left_boundary, right_boundary,
                               left_boundary_derivatives, right_boundary_derivatives,
                               lower_coef, central_coef, upper_coef,
                               left_weights, right_weights, mode, 1, order, source)
    elseif order == 12
        # interior stencil
        upper_coef = SVector(T(6 // 7), T(-15 // 56), T(5 // 63), T(-1 // 56), T(1 // 385),
                             T(-1 // 5544))
        central_coef = zero(T)
        lower_coef = -upper_coef

        # The diagonal norm `H` and the antisymmetric `Q` of the boundary
        # closure as printed in the paper, read as exact rational numbers.
        h1 = T(13013597111750 // 100000000000000)
        h2 = T(76146045079020 // 100000000000000)
        h3 = T(11984222247012 // 10000000000000)
        h4 = T(13340123109301 // 10000000000000)
        h5 = T(10951811473364 // 10000000000000)
        h6 = T(97569096377130 // 100000000000000)
        h7 = T(10061945410831 // 10000000000000)
        h8 = T(99874339446564 // 100000000000000)
        h9 = T(10001702615573 // 10000000000000)
        h10 = T(99998873424721 // 100000000000000)
        left_weights = SVector(h1, h2, h3, h4, h5, h6, h7, h8, h9, h10)

        q1_2 = T(67603132599815 // 100000000000000)
        q1_3 = T(-26781065957921 // 100000000000000)
        q1_4 = T(14050310470012 // 100000000000000)
        q1_5 = T(-54072653004710 // 1000000000000000)
        q1_6 = T(-11876984028213 // 1000000000000000)
        q1_7 = T(26300694680362 // 1000000000000000)
        q1_8 = T(-98077210531438 // 10000000000000000)
        q1_9 = T(42848959311712 // 100000000000000000)
        q1_10 = T(30440269352791 // 100000000000000000)
        q2_3 = T(95204118058043 // 100000000000000)
        q2_4 = T(-41306598236120 // 100000000000000)
        q2_5 = T(15442577883533 // 100000000000000)
        q2_6 = T(26535212157067 // 1000000000000000)
        q2_7 = T(-67869317213141 // 1000000000000000)
        q2_8 = T(26431850942376 // 1000000000000000)
        q2_9 = T(-18383496124689 // 10000000000000000)
        q2_10 = T(-62904733024363 // 100000000000000000)
        q3_4 = T(94424869445124 // 100000000000000)
        q3_5 = T(-30369922793820 // 100000000000000)
        q3_6 = T(-17036409572828 // 1000000000000000)
        q3_7 = T(97546158402857 // 1000000000000000)
        q3_8 = T(-42534720340735 // 1000000000000000)
        q3_9 = T(53471186513813 // 10000000000000000)
        q3_10 = T(35890734751923 // 100000000000000000)
        q4_5 = T(81369662782755 // 100000000000000)
        q4_6 = T(-84027084126181 // 1000000000000000)
        q4_7 = T(-10721180825279 // 100000000000000)
        q4_8 = T(61098180874949 // 1000000000000000)
        q4_9 = T(-12618762739267 // 1000000000000000)
        q4_10 = T(74866320589496 // 100000000000000000)
        q5_6 = T(68140317057259 // 100000000000000)
        q5_7 = T(-50090848997730 // 1000000000000000)
        q5_8 = T(-32156238350691 // 1000000000000000)
        q5_9 = T(12270208460707 // 1000000000000000)
        q5_10 = T(-89539078453821 // 100000000000000000)
        q6_7 = T(73535220394540 // 100000000000000)
        q6_8 = T(-17565390898074 // 100000000000000)
        q6_9 = T(45853976429252 // 1000000000000000)
        q6_10 = T(-12971393808506 // 1000000000000000)
        q7_8 = T(82185236816776 // 100000000000000)
        q7_9 = T(-24842386107781 // 100000000000000)
        q7_10 = T(76038690915127 // 1000000000000000)
        q8_9 = T(85207110387533 // 100000000000000)
        q8_10 = T(-26676625654053 // 100000000000000)
        q9_10 = T(85702210251244 // 100000000000000)

        # `D[i, :] = (Q[i, :] - δ₁ᵢ e₁ᵀ / 2) / H[i, i]`. The entries reaching
        # into the uniform part of the grid are fixed by the interior stencil,
        # `Q[i, j] = upper_coef[j - i]`, since `H[j, j] = 1` there.
        left_boundary = (
                         # d1
                         DerivativeCoefficientRow{T, 1, 10}(SVector(-T(1 // 2) / h1,
                                                                    q1_2 / h1,
                                                                    q1_3 / h1,
                                                                    q1_4 / h1,
                                                                    q1_5 / h1,
                                                                    q1_6 / h1,
                                                                    q1_7 / h1,
                                                                    q1_8 / h1,
                                                                    q1_9 / h1,
                                                                    q1_10 / h1)),
                         # d2
                         DerivativeCoefficientRow{T, 1, 10}(SVector(-q1_2 / h2,
                                                                    T(0),
                                                                    q2_3 / h2,
                                                                    q2_4 / h2,
                                                                    q2_5 / h2,
                                                                    q2_6 / h2,
                                                                    q2_7 / h2,
                                                                    q2_8 / h2,
                                                                    q2_9 / h2,
                                                                    q2_10 / h2)),
                         # d3
                         DerivativeCoefficientRow{T, 1, 10}(SVector(-q1_3 / h3,
                                                                    -q2_3 / h3,
                                                                    T(0),
                                                                    q3_4 / h3,
                                                                    q3_5 / h3,
                                                                    q3_6 / h3,
                                                                    q3_7 / h3,
                                                                    q3_8 / h3,
                                                                    q3_9 / h3,
                                                                    q3_10 / h3)),
                         # d4
                         DerivativeCoefficientRow{T, 1, 10}(SVector(-q1_4 / h4,
                                                                    -q2_4 / h4,
                                                                    -q3_4 / h4,
                                                                    T(0),
                                                                    q4_5 / h4,
                                                                    q4_6 / h4,
                                                                    q4_7 / h4,
                                                                    q4_8 / h4,
                                                                    q4_9 / h4,
                                                                    q4_10 / h4)),
                         # d5
                         DerivativeCoefficientRow{T, 1, 11}(SVector(-q1_5 / h5,
                                                                    -q2_5 / h5,
                                                                    -q3_5 / h5,
                                                                    -q4_5 / h5,
                                                                    T(0),
                                                                    q5_6 / h5,
                                                                    q5_7 / h5,
                                                                    q5_8 / h5,
                                                                    q5_9 / h5,
                                                                    q5_10 / h5,
                                                                    upper_coef[6] / h5)),
                         # d6
                         DerivativeCoefficientRow{T, 1, 12}(SVector(-q1_6 / h6,
                                                                    -q2_6 / h6,
                                                                    -q3_6 / h6,
                                                                    -q4_6 / h6,
                                                                    -q5_6 / h6,
                                                                    T(0),
                                                                    q6_7 / h6,
                                                                    q6_8 / h6,
                                                                    q6_9 / h6,
                                                                    q6_10 / h6,
                                                                    upper_coef[5] / h6,
                                                                    upper_coef[6] / h6)),
                         # d7
                         DerivativeCoefficientRow{T, 1, 13}(SVector(-q1_7 / h7,
                                                                    -q2_7 / h7,
                                                                    -q3_7 / h7,
                                                                    -q4_7 / h7,
                                                                    -q5_7 / h7,
                                                                    -q6_7 / h7,
                                                                    T(0),
                                                                    q7_8 / h7,
                                                                    q7_9 / h7,
                                                                    q7_10 / h7,
                                                                    upper_coef[4] / h7,
                                                                    upper_coef[5] / h7,
                                                                    upper_coef[6] / h7)),
                         # d8
                         DerivativeCoefficientRow{T, 1, 14}(SVector(-q1_8 / h8,
                                                                    -q2_8 / h8,
                                                                    -q3_8 / h8,
                                                                    -q4_8 / h8,
                                                                    -q5_8 / h8,
                                                                    -q6_8 / h8,
                                                                    -q7_8 / h8,
                                                                    T(0),
                                                                    q8_9 / h8,
                                                                    q8_10 / h8,
                                                                    upper_coef[3] / h8,
                                                                    upper_coef[4] / h8,
                                                                    upper_coef[5] / h8,
                                                                    upper_coef[6] / h8)),
                         # d9
                         DerivativeCoefficientRow{T, 1, 15}(SVector(-q1_9 / h9,
                                                                    -q2_9 / h9,
                                                                    -q3_9 / h9,
                                                                    -q4_9 / h9,
                                                                    -q5_9 / h9,
                                                                    -q6_9 / h9,
                                                                    -q7_9 / h9,
                                                                    -q8_9 / h9,
                                                                    T(0),
                                                                    q9_10 / h9,
                                                                    upper_coef[2] / h9,
                                                                    upper_coef[3] / h9,
                                                                    upper_coef[4] / h9,
                                                                    upper_coef[5] / h9,
                                                                    upper_coef[6] / h9)),
                         # d10
                         DerivativeCoefficientRow{T, 1, 16}(SVector(-q1_10 / h10,
                                                                    -q2_10 / h10,
                                                                    -q3_10 / h10,
                                                                    -q4_10 / h10,
                                                                    -q5_10 / h10,
                                                                    -q6_10 / h10,
                                                                    -q7_10 / h10,
                                                                    -q8_10 / h10,
                                                                    -q9_10 / h10,
                                                                    T(0),
                                                                    upper_coef[1] / h10,
                                                                    upper_coef[2] / h10,
                                                                    upper_coef[3] / h10,
                                                                    upper_coef[4] / h10,
                                                                    upper_coef[5] / h10,
                                                                    upper_coef[6] / h10)))
        right_boundary = .-left_boundary
        right_weights = left_weights
        left_boundary_derivatives = Tuple{}()
        right_boundary_derivatives = left_boundary_derivatives

        DerivativeCoefficients(left_boundary, right_boundary,
                               left_boundary_derivatives, right_boundary_derivatives,
                               lower_coef, central_coef, upper_coef,
                               left_weights, right_weights, mode, 1, order, source)
    else
        throw(ArgumentError("Order $order not implemented/derived."))
    end
end
