[deps]
BandedMatrices = "aae01518-5342-5314-be14-df237901396f"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
DiffEqOperators = "9fdde737-9c7f-55bf-ade8-46b3f136cc48"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"

[compat]
BandedMatrices = "0.15, 0.16, 0.17"
BenchmarkTools = "0.5, 0.7, 1.0 - 1.2.0, 1.2.2"
DiffEqOperators = "4.26"
Documenter = "1"
ForwardDiff = "0.10"
LaTeXStrings = "1.2"
OrdinaryDiffEq = "5.50, 6"
Plots = "1.9"
StaticArrays = "1.2"
StructArrays = "0.5, 0.6"

[preferences.OrdinaryDiffEq]
PrecompileAutoSpecialize = false
PrecompileAutoSwitch = false
PrecompileDefaultSpecialize = false
PrecompileFunctionWrapperSpecialize = false
PrecompileLowStorage = false
PrecompileNoSpecialize = false
PrecompileNonStiff = false
PrecompileStiff = false
